import { delay } from '@/lib/delay'
import { localDateISO } from '@/lib/format'
import type { Student, StudentEditInput } from '@/types'
import { RepositoryError } from '../errors'
import type { AdminStudent, StudentRepository } from '../types'
import { db, pad5 } from './db'

/**
 * Prototype hook for testing the error state: submit with admission number "FAIL".
 * A real repository would surface network/database errors the same way (by rejecting).
 */
export const MOCK_FAILURE_ADMISSION_NO = 'FAIL'

/** Required editable fields. The reference number, school, id and timestamps are intentionally absent. */
const REQUIRED_KEYS = ['name', 'fatherName', 'motherName', 'dob', 'className', 'section', 'rollNo', 'admissionNo', 'address', 'mobile'] as const
/** Optional fields: an empty value clears them (stored as undefined). */
const OPTIONAL_KEYS = ['bloodGroup', 'houseName', 'houseColour', 'busRoute', 'busStoppage'] as const

/** Joins the school by ID. Historical records of inactive schools stay fully visible. */
function withSchool(student: Student): AdminStudent {
  const school = db.schools.find((s) => s.id === student.schoolId)
  return { ...student, schoolName: school?.name ?? 'Unknown school', schoolCode: school?.code ?? '-', schoolActive: school?.isActive ?? false }
}

const find = (id: string) => {
  const student = db.students.find((s) => s.id === id)
  if (!student) throw new RepositoryError('not_found', 'Student not found.')
  return student
}

const sameText = (a: string, b: string) => a.trim().toLowerCase() === b.trim().toLowerCase()

export const mockStudentRepository: StudentRepository = {
  async submit(input) {
    await delay(1400)
    if (input.admissionNo.toUpperCase() === MOCK_FAILURE_ADMISSION_NO) {
      throw new Error('Mock submission failure')
    }

    // The school is re-checked here, never trusted from the URL or the form. The real backend must
    // do the same independently (and enforce it with database permissions / row-level security).
    const school = db.schools.find((s) => s.id === input.schoolId)
    if (!school || !school.isActive) {
      throw new RepositoryError('school_unavailable', 'This school is not accepting submissions.')
    }

    const submittedAt = new Date().toISOString()
    // Reference numbers are generated by the data layer, never by UI code. They count archived students
    // too, so a number is never reused.
    const referenceNo = `ANU-${new Date().getFullYear()}-${pad5(db.students.length + 1)}`
    const { photo, ...fields } = input
    db.students.push({
      ...fields,
      id: crypto.randomUUID(),
      referenceNo,
      // The prototype keeps the photo only as a browser object URL, valid until the page is refreshed.
      photoUrl: typeof URL.createObjectURL === 'function' ? URL.createObjectURL(photo) : undefined,
      submittedAt,
      updatedAt: submittedAt,
      isArchived: false,
    })
    return { referenceNo, submittedAt, schoolName: school.name }
  },

  async list({ search = '', schoolId, className, section, status = 'active', submittedFrom, submittedTo, page = 1, pageSize = 10 } = {}) {
    await delay(250)
    const q = search.trim().toLowerCase()
    const matches = db.students
      .filter((s) => (status === 'all' ? true : status === 'archived' ? s.isArchived : !s.isArchived))
      .filter((s) => !schoolId || s.schoolId === schoolId)
      .filter((s) => !className || s.className === className)
      .filter((s) => !section || sameText(s.section, section))
      .filter((s) => {
        if (!submittedFrom && !submittedTo) return true
        const day = localDateISO(s.submittedAt)
        return (!submittedFrom || day >= submittedFrom) && (!submittedTo || day <= submittedTo)
      })
      .filter(
        (s) =>
          !q ||
          [s.name, s.referenceNo, s.admissionNo, s.rollNo].some((v) => v.toLowerCase().includes(q)),
      )
      .sort((a, b) => b.submittedAt.localeCompare(a.submittedAt) || b.referenceNo.localeCompare(a.referenceNo))

    const total = matches.length
    const size = Math.max(1, pageSize)
    const totalPages = Math.max(1, Math.ceil(total / size))
    const current = Math.min(Math.max(1, page), totalPages) // out-of-range pages (e.g. after archiving the last row) clamp
    return {
      items: matches.slice((current - 1) * size, current * size).map(withSchool),
      total,
      page: current,
      pageSize: size,
      totalPages,
      counts: { active: db.students.filter((s) => !s.isArchived).length, archived: db.students.filter((s) => s.isArchived).length },
    }
  },

  async getDetail(id) {
    await delay(250)
    const student = find(id)
    return {
      student: withSchool(student),
      schoolOrders: db.orders.filter((o) => o.schoolId === student.schoolId).sort((a, b) => b.orderDate.localeCompare(a.orderDate)).map((o) => ({ ...o })),
    }
  },

  async update(id, input) {
    await delay(500)
    const student = find(id)

    // Assumption: an admission number identifies a student within a school. Public submissions are not
    // blocked (parents may resubmit corrections), so duplicates can already exist; the rule is only
    // enforced when an admin CHANGES the number, and only against non-archived students of the same school.
    if (!sameText(input.admissionNo, student.admissionNo)) {
      const clash = db.students.some(
        (s) => s.id !== id && s.schoolId === student.schoolId && !s.isArchived && sameText(s.admissionNo, input.admissionNo),
      )
      if (clash) throw new RepositoryError('duplicate_admission_no', `Admission number ${input.admissionNo} is already used by another student of this school.`)
    }

    // Build the whole next state first, then assign in one step, so a failure can never leave a half-edited record.
    const next: Partial<Student> = {}
    for (const k of REQUIRED_KEYS) next[k] = input[k as keyof StudentEditInput] as string
    for (const k of OPTIONAL_KEYS) next[k] = input[k] || undefined
    Object.assign(student, next, { updatedAt: new Date().toISOString() })
    return { ...student }
  },

  async setArchived(id, archived) {
    await delay(400)
    const student = find(id)
    const now = new Date().toISOString()
    student.isArchived = archived
    student.archivedAt = archived ? now : undefined
    student.updatedAt = now
    return { ...student }
  },

  async getFilterOptions() {
    await delay(100)
    return { sections: [...new Set(db.students.map((s) => s.section.toUpperCase()))].sort() }
  },
}
