import { delay } from '@/lib/delay'
import type { Student } from '@/types'
import type { StudentRepository } from '../types'

/** In-memory only. Cleared on page refresh; no browser persistence by design. */
const submissions: Student[] = []

/**
 * Prototype hook for testing the error state: submit with admission number "FAIL".
 * A real repository would surface network/database errors the same way (by rejecting).
 */
export const MOCK_FAILURE_ADMISSION_NO = 'FAIL'

const pad = (n: number) => String(n).padStart(5, '0')

export const mockStudentRepository: StudentRepository = {
  async submit(input) {
    await delay(1400)
    if (input.admissionNo.toUpperCase() === MOCK_FAILURE_ADMISSION_NO) {
      throw new Error('Mock submission failure')
    }
    const submittedAt = new Date().toISOString()
    // Reference numbers are generated by the data layer, never by UI code.
    const referenceNo = `ANU-${new Date().getFullYear()}-${pad(submissions.length + 1)}`
    const { photo, ...fields } = input
    void photo // a real repository would upload this; the prototype does not keep files
    submissions.push({ ...fields, id: crypto.randomUUID(), referenceNo, submittedAt })
    return { referenceNo, submittedAt }
  },
}
